/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5b29e58cf7a005e2af76398d9abdc796)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	OIDC_AUDIENCE: "api.dev.polygon-dev.technology";
	OIDC_ISSUER: "https://oms-server-wallet-dashboard.0xsequence.workers.dev";
	APP_ORIGIN: "https://oms-server-wallet-dashboard.0xsequence.workers.dev";
	TRUSTED_PCR0S: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
	OIDC_ADDITIONAL_PUBLIC_JWKS: "";
	TRAILS_API_URL: "https://trails-api.sequence.app";
	TRAILS_PROJECT_ID: "oms-dashboard";
	SWAPS_ENABLED: "true";
	WALLETS: DurableObjectNamespace<import("./apps/server/worker").WalletCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./apps/server/worker");
		durableNamespaces: "WalletCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OIDC_AUDIENCE" | "OIDC_ISSUER" | "APP_ORIGIN" | "TRUSTED_PCR0S" | "OIDC_ADDITIONAL_PUBLIC_JWKS" | "TRAILS_API_URL" | "TRAILS_PROJECT_ID" | "SWAPS_ENABLED">> {}
}
